name: iban_form_field
description: An IBAN form which deals with spacing and country specific rules.
version: 0.2.0
homepage: https://github.com/inapay/iban_form_field

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  iban: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
  flutter_test:
    sdk: flutter

