name: iban_form_field
description: An IBAN form which deals with spacing and country specific rules.
# version: 1.0.0
# homepage: https://www.example.com
# author: Harm Aarts <harm@aarts.email>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  flutter_test:
    sdk: flutter

